// user actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const TOKEN_LOGIN_ERROR = "TOKEN_LOGIN_ERROR";
export const INFO_FILLED_ERROR = "INFO_FILLED_ERROR";

// users actions
export const USERS_FETCHED_SUCCESS = "USERS_FETCHED_SUCCESS";
export const USERS_FETCHED_ERROR = "USERS_FETCHED_ERROR";
export const USERS_LIKE_ERROR = "USERS_LIKE_ERROR";
export const USER_LIKE_SUCCESS = "USER_LIKE_SUCCESS";
export const USER_DISLIKE_SUCCESS = "USER_DISLIKE_SUCCESS";
export const USER_DISLIKE_ERROR = "USER_DISLIKE_ERROR";

// user settings actions
export const SEARCH_FETCH_SUCCESS = "SEARCH_FETCH_SUCCESS";
export const SEARCH_FETCH_ERROR = "SEARCH_FETCH_ERROR";
export const SEARCH_UPDATE_SUCCESS = "SEARCH_UPDATE_SUCCESS";
export const SEARCH_UPDATE_ERROR = "SEARCH_UPDATE_ERROR";
