// user actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_REDUCER_ERROR = "LOGIN_REDUCER_ERROR";
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";

// users actions
export const USERS_FETCHED_SUCCESS = "USERS_FETCHED_SUCCESS";
export const USER_LIKE_SUCCESS = "USER_LIKE_SUCCESS";
export const USER_DISLIKE_SUCCESS = "USER_DISLIKE_SUCCESS";
export const USER_REPORT_SUCCESS = "USER_REPORT_SUCCESS";
export const DELETE_REPORTED_USER = "DELETE_REPORTED_USER";
export const USERS_REDUCER_ERROR = "USERS_REDUCER_ERROR";

// users images actions
export const IMAGES_FETCH_SUCCESS = "IMAGES_FETCH_SUCCESS";
export const IMAGES_REDUCER_ERROR = "IMAGES_REDUCER_ERROR";
export const CLEAR_STORE_IMAGES = "CLEAR_STORE_IMAGES";

// user settings actions
export const SEARCH_FETCH_SUCCESS = "SEARCH_FETCH_SUCCESS";
export const SEARCH_UPDATE_SUCCESS = "SEARCH_UPDATE_SUCCESS";
export const SEARCH_REDUCER_ERROR = "SEARCH_REDUCER_ERROR";
